#ifndef PATCEGFX_appvar_include_file
#define PATCEGFX_appvar_include_file

#ifdef __cplusplus
extern "C" {
#endif

#define sizeof_global_palette 22
#define global_palette (PATCEGFX_appvar[0])
#define symbols_palette_offset 0
#define club_large_width 16
#define club_large_height 11
#define PATCEGFX_symbols_club_large_index 1
#define club_large ((gfx_sprite_t*)PATCEGFX_appvar[1])
#define club_medium_width 8
#define club_medium_height 5
#define PATCEGFX_symbols_club_medium_index 2
#define club_medium ((gfx_sprite_t*)PATCEGFX_appvar[2])
#define club_small_width 8
#define club_small_height 4
#define PATCEGFX_symbols_club_small_index 3
#define club_small ((gfx_sprite_t*)PATCEGFX_appvar[3])
#define diamond_large_width 16
#define diamond_large_height 11
#define PATCEGFX_symbols_diamond_large_index 4
#define diamond_large ((gfx_sprite_t*)PATCEGFX_appvar[4])
#define diamond_medium_width 8
#define diamond_medium_height 5
#define PATCEGFX_symbols_diamond_medium_index 5
#define diamond_medium ((gfx_sprite_t*)PATCEGFX_appvar[5])
#define diamond_small_width 8
#define diamond_small_height 4
#define PATCEGFX_symbols_diamond_small_index 6
#define diamond_small ((gfx_sprite_t*)PATCEGFX_appvar[6])
#define heart_large_width 16
#define heart_large_height 11
#define PATCEGFX_symbols_heart_large_index 7
#define heart_large ((gfx_sprite_t*)PATCEGFX_appvar[7])
#define heart_medium_width 8
#define heart_medium_height 5
#define PATCEGFX_symbols_heart_medium_index 8
#define heart_medium ((gfx_sprite_t*)PATCEGFX_appvar[8])
#define heart_small_width 8
#define heart_small_height 4
#define PATCEGFX_symbols_heart_small_index 9
#define heart_small ((gfx_sprite_t*)PATCEGFX_appvar[9])
#define spade_large_width 16
#define spade_large_height 11
#define PATCEGFX_symbols_spade_large_index 10
#define spade_large ((gfx_sprite_t*)PATCEGFX_appvar[10])
#define spade_medium_width 8
#define spade_medium_height 5
#define PATCEGFX_symbols_spade_medium_index 11
#define spade_medium ((gfx_sprite_t*)PATCEGFX_appvar[11])
#define spade_small_width 8
#define spade_small_height 4
#define PATCEGFX_symbols_spade_small_index 12
#define spade_small ((gfx_sprite_t*)PATCEGFX_appvar[12])
#define digits_palette_offset 0
#define digit_ace_width 5
#define digit_ace_height 4
#define PATCEGFX_digits_digit_ace_index 13
#define digit_ace ((gfx_sprite_t*)PATCEGFX_appvar[13])
#define digit_eight_width 5
#define digit_eight_height 4
#define PATCEGFX_digits_digit_eight_index 14
#define digit_eight ((gfx_sprite_t*)PATCEGFX_appvar[14])
#define digit_five_width 5
#define digit_five_height 4
#define PATCEGFX_digits_digit_five_index 15
#define digit_five ((gfx_sprite_t*)PATCEGFX_appvar[15])
#define digit_four_width 5
#define digit_four_height 4
#define PATCEGFX_digits_digit_four_index 16
#define digit_four ((gfx_sprite_t*)PATCEGFX_appvar[16])
#define digit_nine_width 5
#define digit_nine_height 4
#define PATCEGFX_digits_digit_nine_index 17
#define digit_nine ((gfx_sprite_t*)PATCEGFX_appvar[17])
#define digit_seven_width 5
#define digit_seven_height 4
#define PATCEGFX_digits_digit_seven_index 18
#define digit_seven ((gfx_sprite_t*)PATCEGFX_appvar[18])
#define digit_six_width 5
#define digit_six_height 4
#define PATCEGFX_digits_digit_six_index 19
#define digit_six ((gfx_sprite_t*)PATCEGFX_appvar[19])
#define digit_ten_width 5
#define digit_ten_height 4
#define PATCEGFX_digits_digit_ten_index 20
#define digit_ten ((gfx_sprite_t*)PATCEGFX_appvar[20])
#define digit_three_width 5
#define digit_three_height 4
#define PATCEGFX_digits_digit_three_index 21
#define digit_three ((gfx_sprite_t*)PATCEGFX_appvar[21])
#define digit_two_width 5
#define digit_two_height 4
#define PATCEGFX_digits_digit_two_index 22
#define digit_two ((gfx_sprite_t*)PATCEGFX_appvar[22])
#define faces_palette_offset 0
#define jack_clubs_width 27
#define jack_clubs_height 39
#define PATCEGFX_faces_jack_clubs_index 23
#define jack_clubs ((gfx_rletsprite_t*)PATCEGFX_appvar[23])
#define jack_diamonds_width 27
#define jack_diamonds_height 39
#define PATCEGFX_faces_jack_diamonds_index 24
#define jack_diamonds ((gfx_rletsprite_t*)PATCEGFX_appvar[24])
#define jack_hearts_width 27
#define jack_hearts_height 39
#define PATCEGFX_faces_jack_hearts_index 25
#define jack_hearts ((gfx_rletsprite_t*)PATCEGFX_appvar[25])
#define jack_spades_width 27
#define jack_spades_height 39
#define PATCEGFX_faces_jack_spades_index 26
#define jack_spades ((gfx_rletsprite_t*)PATCEGFX_appvar[26])
#define king_clubs_width 27
#define king_clubs_height 39
#define PATCEGFX_faces_king_clubs_index 27
#define king_clubs ((gfx_rletsprite_t*)PATCEGFX_appvar[27])
#define king_diamonds_width 27
#define king_diamonds_height 39
#define PATCEGFX_faces_king_diamonds_index 28
#define king_diamonds ((gfx_rletsprite_t*)PATCEGFX_appvar[28])
#define king_hearts_width 27
#define king_hearts_height 39
#define PATCEGFX_faces_king_hearts_index 29
#define king_hearts ((gfx_rletsprite_t*)PATCEGFX_appvar[29])
#define king_spades_width 27
#define king_spades_height 39
#define PATCEGFX_faces_king_spades_index 30
#define king_spades ((gfx_rletsprite_t*)PATCEGFX_appvar[30])
#define queen_clubs_width 27
#define queen_clubs_height 39
#define PATCEGFX_faces_queen_clubs_index 31
#define queen_clubs ((gfx_rletsprite_t*)PATCEGFX_appvar[31])
#define queen_diamonds_width 27
#define queen_diamonds_height 39
#define PATCEGFX_faces_queen_diamonds_index 32
#define queen_diamonds ((gfx_rletsprite_t*)PATCEGFX_appvar[32])
#define queen_hearts_width 27
#define queen_hearts_height 39
#define PATCEGFX_faces_queen_hearts_index 33
#define queen_hearts ((gfx_rletsprite_t*)PATCEGFX_appvar[33])
#define queen_spades_width 27
#define queen_spades_height 39
#define PATCEGFX_faces_queen_spades_index 34
#define queen_spades ((gfx_rletsprite_t*)PATCEGFX_appvar[34])
#define card_back_palette_offset 0
#define card_back_width 29
#define card_back_height 41
#define PATCEGFX_card_back_card_back_index 35
#define card_back ((gfx_sprite_t*)PATCEGFX_appvar[35])
#define PATCEGFX_entries_num 36
extern unsigned char *PATCEGFX_appvar[36];
unsigned char PATCEGFX_init(void);

#ifdef __cplusplus
}
#endif

#endif
